const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const {execFileSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'ui.js'), 'utf8');
const script = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n').replace("initUI();\ngo(location.hash.slice(1)||'week');",'');
new vm.Script(script); new vm.Script(ui);
function context(demo){
  const storage = new Map();
  const nodes = new Map();
  const document = {querySelectorAll:()=>[],getElementById:id=>{if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}};
  const ctx = vm.createContext({document,navigator:{},location:{search:demo?'?demo=1':'',hash:''},URLSearchParams,console,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},Date,Math,JSON,crypto:require('node:crypto').webcrypto});
  vm.runInContext(fs.readFileSync(path.join(root,'history.js'),'utf8'),ctx);vm.runInContext(ui,ctx);vm.runInContext(script,ctx);
  return {ctx,storage};
}
const normal=context(false);
assert.equal(vm.runInContext('STORE_KEY',normal.ctx),'xepca_v1');
assert.equal(vm.runInContext('DB.employees.length',normal.ctx),0);
const demo=context(true);
assert.equal(vm.runInContext('STORE_KEY',demo.ctx),'xepca_ui_demo_v1');
vm.runInContext('DB=makeDemoData();save()',demo.ctx);
assert.equal(demo.storage.has('xepca_v1'),false);
assert.equal(vm.runInContext('DB.employees.length',demo.ctx),18);
const modeHeader=vm.runInContext('renderPocketHeader(curMonday)',demo.ctx);
for(const label of ['Theo ngày','Theo nhân viên','Tổng kết tuần','Thao tác'])assert.ok(modeHeader.includes(label));
assert.equal((modeHeader.match(/aria-pressed=/g)||[]).length,3);
assert.ok(!html.includes('id="vwDay"'));
assert.ok(html.includes('<title>Lịch bơi — Ver 2.0</title>'));
assert.equal(JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8')).short_name,'Lịch bơi');
assert.match(vm.runInContext("prettyShiftTime('7h-12h30')",demo.ctx),/07:00.*12:30/);
assert.match(vm.runInContext("prettyShiftTime('19h-00h')",demo.ctx),/19:00.*00:00/);
assert.match(ui,/openSimpleSchedule/);
assert.match(vm.runInContext('weekSummary(curMonday)',demo.ctx),/111/);
assert.equal((vm.runInContext('renderPeopleSchedule(curMonday)',demo.ctx).match(/data-cell-emp=/g)||[]).length,126);
assert.equal((vm.runInContext('renderMobilePeople(curMonday)',demo.ctx).match(/data-person-day=/g)||[]).length,7);
assert.match(vm.runInContext('weekSummary(curMonday)',demo.ctx),/<details class="week-totals">/);
vm.runInContext("selectedPerson='demo-1'",demo.ctx);
assert.match(vm.runInContext('renderMobilePeople(curMonday)',demo.ctx),/data-person-emp="demo-1"/);
assert.equal(vm.runInContext("noAccent('Nguyễn Minh Anh')",demo.ctx),'nguyen minh anh');
assert.equal(vm.runInContext("parseCSV('Tên,Vị trí\\n\"An, Bình\",Pha chế')[1][0]",demo.ctx),'An, Bình');
vm.runInContext("setCell(curMonday,'demo-0',0,[{typeId:'s2',pos:'Pha chế',lock:true}]);save()",demo.ctx);
assert.equal(vm.runInContext("cellShifts(curMonday,'demo-0',0)[0].typeId",demo.ctx),'s2');
assert.equal(JSON.parse(demo.storage.get('xepca_ui_demo_v1')).schedule[vm.runInContext('weekKey(curMonday)',demo.ctx)]['demo-0'][0][0].lock,true);
assert.match(vm.runInContext('renderPeopleSchedule(curMonday)',demo.ctx),/aria-label="Minh Anh, Thứ Hai, 12h30-17h30"/);
const before=execFileSync('git',['show','HEAD:index.html'],{cwd:root,encoding:'utf8'});
const algorithm=s=>s.slice(s.indexOf('function runAutoSchedule('),s.indexOf('function autoScheduleBtn(')).replace(/\r\n/g,'\n');
assert.equal(algorithm(html),algorithm(before),'Existing auto-scheduler remains unchanged');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
for(const asset of ['ui.css','ui.js'])assert.ok(sw.includes("'"+asset+"'"));
console.log('PASS: script syntax, storage isolation, demo data, 126 schedule cells, search, CSV, assignment persistence, unchanged scheduler, offline assets.');
